server:
  port: 9001
  shutdown: graceful
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

spring:
  application:
    name: catalog-service
  lifecycle:
    timeout-per-shutdown-phase: 15s
  datasource:
    username: postgres
    password: admin
    url: 'jdbc:postgresql://localhost:5432/polardb_catalog'
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5
          
logging:
   pattern:
      level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

management:
   endpoints:
      web:
         exposure:
            include: '*'
   endpoint:
      health:
         show-details: always
         show-components: always
         probes:
            enabled: true
   info:
      env:
         enabled: true
      java:
         enabled: true
      os:
         enabled: true
   metrics:
      tags:
         application: ${spring.application.name}
polar:
  greeting: Welcome to the local book catalog!

