name: Acceptance Stage
on:
  workflow_run:
    workflows: ['Commit Stage']
    types: [completed]
    branches: [main, dev]
concurrency: acceptance

env:
  REGISTRY: ghcr.io
  OWNER: upen28
  APP_REPO: ${{ github.event.workflow_run.head_repository}}
  IMAGE_NAME: polar-bookshop/${{ github.event.workflow_run.head_repository }}
  VERSION: ${{ github.event.workflow_run.head_sha }}
  BRANCH_NAME: ${{ github.event.workflow_run.head_branch == 'refs/heads/main' && 'production' || 'development' }}
  
  DEPLOY_REPO: polar-deployment-2

  run: echo REGISTRY ,OWNER, APP_REPO, IMAGE_NAME, VERSION, BRANCH_NAME, DEPLOY_REPO
  

jobs:
  deliver:
    name: Deliver Release Candidate to BRANCH_NAME
    runs-on: ubuntu-latest
    steps:
      - name: Deliver Application to Production
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.DISPATCH_TOKEN }}
          repository: ${{ env.OWNER }}/${{ env.DEPLOY_REPO }}
          event-type: app_delivery
          client-payload: '{
            "app_image": "${{ env.REGISTRY }}/${{ env.OWNER }}/${{ env.IMAGE_NAME }}",
            "app_version": "${{ env.VERSION }}", 
            "app_name": "${{ env.APP_REPO }}",
            "app-dir-name": ${{env.BRANCH_NAME}} 
            }'              