name: Commit Stage
on: [workflow_dispatch]
env:
  REGISTRY: ghcr.io
  USER_NAME: upen28
  IMAGE_NAME: polar-bookshop/${{ github.event.repository.name }}/${{ github.ref_name}}
  VERSION: ${{ github.sha }}

jobs:
  build:
    name: SCAN(Trivy), [BUILD, UNIT TEST, INTEGRATION TEST](gradle) and TEST COVERAGE(Jacoco)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4.2.1
        env:
          SONAR_TOKEN: ${{ secrets.CLOUD_SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.host.url=${SONAR_HOST_URL}
            -Dsonar.login=${CLOUD_SONAR_TOKEN}
            -Dsonar.organization=upen-ploarbookshop
            -Dsonar.projectKey=polarbook-catalog-service
            -Dsonar.projectName=POLARBOOKSHOP
            -Dsonar.sources=.
            -Dsonar.verbose=true

      

